### ISSUE TITLE
leak with `pari(xxx)`

### ISSUE THREAD

**Issue by videlec** [sagemath/cypari2#81]
As reported in [SageMath trac ticket #27605](https://trac.sagemath.org/ticket/27605#comment:21)
```
>>> import cypari2
>>> pari = cypari2.Pari()
>>> x = pari('1 + 1*I')
>>> complex(x)
(1+1j)
>>> del x
sys:1: RuntimeWarning: cypari2 leaked 48 bytes on the PARI stack
```

**Comment by culler** [comment]
By the way, this is really the opposite of what people usually mean by a "leak".  A leak occurs when memory is allocated but not freed, so the memory footprint grows.  Here allocated memory is being freed (sort of) when it might actually still be in use.

**Comment by culler** [comment]
I think there is a simple solution to this problem.  If there are unwrapped GENS at the bottom of the PARI stack when a Gen object is being deallocated, do not thrown those GENs away.  Instead, ask PARI to repile its stack, discarding the most recently pushed wrapped GEN and moving the unwrapped gens on top of it.  Since the situations which currently lead to the warning appear to be quite rare, this should have minimal impact on performance.  But, as far as I can see, it is safe. 

Here is a patch.
[leak.patch.txt](https://github.com/sagemath/cypari2/files/3442737/leak.patch.txt)

**Comment by jdemeyer** [comment]
The problem is not that we are throwing unwrapped GENs away, the problem is that there are unwrapped GENs in the first place. That's why I said that #83 is solving the wrong problem.

**Comment by videlec** [comment]
Indeed `greal` and `gimag` return **copies** of the real and imaginary parts. One should use `real_i` and `imag_i` instead. See #85.
